### ISSUE TITLE
[QUERY] How to add env variables from CI

### ISSUE THREAD

**Issue by djmgit** [slackapi/deno-slack-sdk#351]
**Question**

How to add env variables from CI?
I am trying the following:
```
slack env add -w ${SLACK_ORG_ID} --token ${SLACK_SERVICE_TOKEN} key val
```
However its throwing the following error:
```
A valid installation of this app is required to take this action (installation_required)

Suggestion

   Install the app with `slack install`
```

However I am running this command after deploying the app using:
```
slack deploy -s -w ${SLACK_ORG_ID} --token ${SLACK_SERVICE_TOKEN}
```
So I believe the app is already installed since I am able to use it as well.

I am using bitbucket pipelines.

**Environment**

cat import_map.json | grep deno-slack
"deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.0/",
"deno-slack-api/": "https://deno.land/x/deno_slack_api@2.7.0/",

deno --version
deno 1.44.4 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5

sw_vers && uname -v
ProductName:		macOS
ProductVersion:		13.6.7
BuildVersion:		22G720
Darwin Kernel Version 22.6.0: Mon Apr 22 20:51:27 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_ARM64_T6020

**Requirements**

**Comment by filmaj** [comment]
Hello @djmgit , I am trying to reproduce this... can you tell me how you retrieved the service token being provided to the deploy and env commands?

**Comment by djmgit** [comment]
@filmaj 
I got the token by running
```slack auth token```
and following the steps from my terminal. I am using the same in the pipelines as well.

Following is the single pipeline step

```
- step: &deploy-slack-workflows-stage
      name: Deploy slack workflow to stage
      script:
        - curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash
        - slack --version
        - cd slack_deno/workflows
        - slack deploy -s -w ${SLACK_ORG_ID} --token ${SLACK_SERVICE_TOKEN}
        - slack env add -w ${SLACK_ORG_ID} --token ${SLACK_SERVICE_TOKEN} key val
```
